// Generated by CoffeeScript 1.6.1
var mainCtrl;

mainCtrl = function($scope, $rootElement, $http, $location) {
  var isProcessing, _i, _ref, _results;
  $scope.slideNumber = 0;
  $scope.dataList = demoData;
  $scope.dataLength = $scope.dataList.length - 1;
  $scope.dataNumbers = (function() {
    _results = [];
    for (var _i = 0, _ref = $scope.dataLength; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);
  $location.url($scope.dataList[$scope.slideNumber].title);
  isProcessing = false;
  $scope.increase = function(model, number) {
    if (number == null) {
      number = 1;
    }
    if (!isProcessing) {
      return $scope[model] += number;
    }
  };
  $scope.decrease = function(model, number) {
    if (number == null) {
      number = 1;
    }
    if (!isProcessing) {
      return $scope[model] -= number;
    }
  };
  $scope.eq = function(model, number) {
    if (!isProcessing) {
      return $scope[model] = number;
    }
  };
  $scope.slide = function(toContent) {
    var _anamateOptions, _animateStyles, _slideWidth;
    if (isProcessing) {
      return;
    }
    isProcessing = true;
    _slideWidth = $('.slideContent', $rootElement).width();
    _animateStyles = {
      marginLeft: "-" + (_slideWidth * toContent) + "px"
    };
    _anamateOptions = {
      duration: 'normal',
      easing: 'swing',
      complete: function() {
        isProcessing = false;
        $location.path($scope.dataList[$scope.slideNumber].title);
        return $scope.$apply();
      }
    };
    return $('.slideContainer', $rootElement).animate(_animateStyles, _anamateOptions);
  };
  return $scope.$watch('slideNumber', function(newVal, oldVal) {
    if (newVal === oldVal) {
      return;
    }
    return $scope.slide(newVal);
  });
};
