// Generated by CoffeeScript 1.4.0
var mainCtrl;

mainCtrl = function($scope) {
  var _i, _ref, _results;
  $scope.$slider = $('#mainSlider');
  $scope.$content = $('#mainContent');
  $scope.slideNumber = 1;
  $scope.isProcessing = false;
  $scope.data = demoData;
  $scope.slideLength = (function() {
    _results = [];
    for (var _i = 0, _ref = $scope.data.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);
  $scope.increase = function(model, number) {
    if (number == null) {
      number = 1;
    }
    if (!$scope.isProcessing) {
      return $scope[model] += number;
    }
  };
  $scope.decrease = function(model, number) {
    if (number == null) {
      number = 1;
    }
    if (!$scope.isProcessing) {
      return $scope[model] -= number;
    }
  };
  $scope.eq = function(model, number) {
    if (!$scope.isProcessing) {
      return $scope[model] = number;
    }
  };
  $scope.slide = function(toContent) {
    var anamateOptions, animateStyles, slideVlue, slideWidth;
    if ($scope.isProcessing) {
      return false;
    }
    $scope.isProcessing = true;
    slideWidth = $scope.$slider.find('.slideContent').width();
    slideVlue = "-" + (slideWidth * toContent) + "px";
    animateStyles = {
      marginLeft: slideVlue
    };
    anamateOptions = {
      duration: 'normal',
      easing: 'swing',
      complete: function() {
        return $scope.isProcessing = false;
      }
    };
    return $('.slideContainer', $scope.$slider).animate(animateStyles, anamateOptions);
  };
  return $scope.$watch('slideNumber', function(newValue, oldValue) {
    return $scope.slide(newValue - 1);
  });
};
