// Generated by CoffeeScript 1.4.0
var demoData;

demoData = [
  {
    url: 'slide_content_01.jpg',
    title: 'jQuery',
    description: 'jQuery is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers. With a combination of versatility and extensibility, jQuery has changed the way that millions of people write JavaScript.'
  }, {
    url: 'slide_content_02.jpg',
    title: 'AngularJS',
    description: 'HTML is great for declaring static documents, but it falters when we try to use it for declaring dynamic views in web-applications. AngularJS lets you extend HTML vocabulary for your application. The resulting environment is extraordinarily expressive, readable, and quick to develop.'
  }, {
    url: 'slide_content_03.jpg',
    title: 'BACKBONE.JS',
    description: 'Backbone.js gives structure to web applications by providing models with key-value binding and custom events, collections with a rich API of enumerable functions, views with declarative event handling, and connects it all to your existing API over a RESTful JSON interface.'
  }, {
    url: 'slide_content_04.jpg',
    title: 'Spine.js',
    description: 'Spine is a lightweight framework for building JavaScript web applications. Spine gives you an MVC structure and then gets out of your way, allowing you to concentrate on the fun stuff, building awesome web applications.'
  }, {
    url: 'slide_content_05.jpg',
    title: 'Flight.js',
    description: 'Flight is a lightweight, component-based JavaScript framework that maps behavior to DOM nodes. Twitter uses it for their web applications. By way of example, we\'ve included a simple email client demo (browse the source) built over the Flight framework.'
  }
];
