// Generated by CoffeeScript 1.4.0

$(function() {
  var $mainSlider, $slideContent, $slideDescription, $slider, changeSlideRelations, checkArrowDisplay, hideArrow, isArrowLeft, isArrowRight, moveActiveClass, showArrow, slide, slideLength, slideNaviList, slideNumber, slideWidth;
  $mainSlider = $('#mainSlider');
  $slider = $('.slideContainer', $mainSlider);
  $slideContent = $('.slideContent', $slider);
  slideNaviList = $('.slideNaviList', $mainSlider);
  $slideDescription = $('.slideDescription', '#mainContent');
  slideWidth = 640;
  slideLength = $slideContent.length;
  slideNumber = 1;
  isArrowLeft = false;
  isArrowRight = true;
  showArrow = function() {
    if (isArrowLeft) {
      $('.arrowLeft', $mainSlider).addClass('ac');
    }
    if (isArrowRight) {
      return $('.arrowRight', $mainSlider).addClass('ac');
    }
  };
  hideArrow = function() {
    return $('.arrowLeft, .arrowRight', $mainSlider).removeClass('ac');
  };
  checkArrowDisplay = function() {
    isArrowLeft = slideNumber !== 1;
    isArrowRight = slideNumber !== slideLength;
    $mainSlider.trigger('mouseleave');
    return $mainSlider.trigger('mouseenter');
  };
  moveActiveClass = function($target) {
    $target.removeClass('ac');
    return $target.eq(slideNumber - 1).addClass('ac');
  };
  changeSlideRelations = function() {
    moveActiveClass(slideNaviList);
    return moveActiveClass($slideDescription);
  };
  slide = function(toContent) {
    var anamateOptions, animateStyles, slideVlue;
    if ($slider.hasClass('sliding')) {
      return false;
    }
    if (toContent === 'left') {
      slideVlue = "+=" + slideWidth + "px";
      --slideNumber;
    }
    if (toContent === 'right') {
      slideVlue = "-=" + slideWidth + "px";
      ++slideNumber;
    }
    if ($.isNumeric(toContent)) {
      slideVlue = "-" + (slideWidth * toContent) + "px";
      slideNumber = ++toContent;
    }
    animateStyles = {
      marginLeft: slideVlue
    };
    anamateOptions = {
      duration: 'normal',
      easing: 'swing',
      complete: function() {
        $(this).removeClass('sliding');
        changeSlideRelations();
        return checkArrowDisplay();
      }
    };
    return $slider.addClass('sliding').animate(animateStyles, anamateOptions);
  };
  return $mainSlider.on('click', '.arrowLeft', function() {
    return slide('left');
  }).on('click', '.arrowRight', function() {
    return slide('right');
  }).on('click', '.slideNaviList', function() {
    return slide($(this).index());
  }).on('mouseenter', function() {
    return showArrow();
  }).on('mouseleave', function() {
    return hideArrow();
  });
});
